name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run:  make

    - name: apt install valgrind
      run: |
        sudo apt-get -y install valgrind

    - name: make test # TODO put run content into a separate shell script you lazy fuck?
      run: |
        valgrind_error_code=5
        valgrind_params="--leak-check=full --error-exitcode=$valgrind_error_code"
        valgrind_run_options=(
          "valgrind $valgrind_params ./bin/run ./resources/adjacencyMatrix3.txt --dijkstra 1 7"
          "valgrind $valgrind_params ./bin/run ./resources/adjacencyMatrix3.txt --bfs 1 7"
          "valgrind $valgrind_params ./bin/run ./resources/missingValuesMatrix.txt --bfs 1 7"
          "valgrind $valgrind_params ./bin/run ./resources/invalidAdjacencyMatrix.txt --bfs 1 7"
        )
        exitcode=0
        for valgrind_run_option in "${valgrind_run_options[@]}"
        do
          $valgrind_run_option
          if [ $? -eq $valgrind_error_code ]; then
            exitcode=1
          fi
        echo "pici $?;"
        done
        exit $exitcode
